version: 2.1

jobs:

#  ------------------------------------------------------------------------------------------------------------------------------------------
#  Build and test application
#  ------------------------------------------------------------------------------------------------------------------------------------------

    build:
      docker:
        - image: python:3.7.3-stretch
      steps:
        - checkout
        - run:
            name: Install pip packages
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt

        - run:
            name: Test with pytest
            command: |
              . venv/bin/activate
              pytest

#  ------------------------------------------------------------------------------------------------------------------------------------------
#  To lint the Dockerfile
#  ------------------------------------------------------------------------------------------------------------------------------------------

    run-lint:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              sudo chmod +x /bin/hadolint
        - run:
            name: Run Lint
            command: |
              hadolint Dockerfile
              
#  ------------------------------------------------------------------------------------------------------------------------------------------
#  Build and Push the Dockerimage for the application 
#  ------------------------------------------------------------------------------------------------------------------------------------------

    build-docker-image:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout

        - setup_remote_docker:
            version: 19.03.13

        - run:
            name: Build and Push Docker Image
            command: |
              export TAG=latest
              export IMAGE_NAME=udacity
              docker build -t duongvcn/$IMAGE_NAME:$TAG .
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
              docker push duongvcn/$IMAGE_NAME:$TAG

# ----------------------------------------------------------------------------------------------------------------------------------------
# Deploy the application to EKS
# ---------------------------------------------------------------------------------------------------------------------------------------
    deploy-infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              yum install -y tar gzip
              curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
              mv /tmp/eksctl /usr/local/bin
              eksctl version
              curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.25.0/bin/linux/amd64/kubectl
              chmod +x ./kubectl
              mv ./kubectl /usr/local/bin/kubectl
        - run:
            name: Deploy application with kubernetes
            command: |
              #eksctl create cluster --name devops-cluster --region=us-east-1
              aws sts get-caller-identity
              aws eks update-kubeconfig --name devops-cluster --region us-east-1
              kubectl get nodes
              kubectl apply -f ./eks/deployment.yaml
              kubectl get pods
              kubectl create -f ./eks/loadbalancer.yaml
              sleep 20
              kubectl get svc
              Kubectl describe pod  | grep "image"
              kubectl run duongvcn-udacity-app --image=duongvcn/udacity:latest --port=8080
              kubectl get pods
              ubectl port-forward duongvcn-udacity-app 8089:80



# ----------------------------------------------------------------------------------------------------------------------------------------
# Start of Workflow
# ----------------------------------------------------------------------------------------------------------------------------------------
     
workflows:
  default:
    jobs:
      - build

      - run-lint:
          requires:
            - build
      
      - build-docker-image:
          requires:
            - run-lint
            
      - deploy-infrastructure:
          requires:
            - build-docker-image