version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest

  docker-image:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push to Docker Hub
          command: |
            dockerpath=duongvcn/udacity:v1.0.0
            docker build -t $dockerpath .
            docker image ls
            echo "Docker ID and Image: $dockerpath"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
            echo "Docker tag Image: $dockerpath"
            docker tag $dockerpath $dockerpath
            echo "Docker push Image: $dockerpath"
            docker push $dockerpath

  create-deployment:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: set-credential
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_session_token $AWS_SESSION_TOKEN
            aws configure set region $AWS_DEFAULT_REGION
      - kubernetes/install-kubectl
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: aws-devops
          install-kubectl: true

workflows:
  default:
    jobs:
      - build
      - docker-image:
          requires:
            - build
      - create-deployment:
          requires:
            - docker-image
          filters: 
            branches:
              only: [master]
      - aws-eks/update-container-image:
          cluster-name: aws-devops
          container-image-updates: 'ml-training=${DOCKERHUB_REPO}/ml-training:${CIRCLE_WORKFLOW_ID:0:7}'
          resource-name: deployment/ml-training-deployment
          requires:
            - create-deployment
