apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-deployment
  namespace: default
  labels:
    app: udacity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity
  template:
    metadata:
      labels:
        app: udacity
    spec:
      serviceAccountName: docker-sa
      containers:
      - name: udacity
        image: duongvcn/udacity:latest
        ports:
          - containerPort: 80