apiVersion: v1
kind: Service
metadata:
  name: udacity-svc
  namespace: default
spec:
  selector:
    app: udacity
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80